### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by fuseraft** [fuseraft/astral#168]
I've been updating docs as much as I can but it could definitely be standardized and better organized. I welcome this as a good first issue.

**Comment by bruhhnitin** [comment]
Hi! I'm a first-timer open to help out, please let me know what I can do to help with documentation with some references as needed.

**Comment by XDreamist** [comment]
I can help you with it. How do you like it to be organized, in which way?

**Comment by fuseraft** [comment]
@bruhhnitin @XDreamist Hey thanks for reaching out to contribute! Here's the [link to the current documentation](https://github.com/fuseraft/kiwi/tree/master/docs). The docs are all in markdown.

Some thoughts for areas of improvement:
- Look for any inconsistencies in formatting, examples, or terminology used across different sections of the docs.
- If you find sections that seem complex or difficult to understand, consider rewriting them for clarity.
- The way I'm documenting `kiwilib` needs to be revamped. I think it would be great to have it presented similar to the documentation on Ruby-Doc.org.
  - Here is [an example of existing `@kiwi/argv` documentation](https://github.com/fuseraft/kiwi/blob/master/docs/kiwilib/argv.md) 
  - Here is [an example from Ruby-Doc.org](https://ruby-doc.org/3.3.0/IO.html#method-c-foreach) 
- Nice to haves:
  - A table-of-contents beneath the summary for each markdown file with jump-links to each section in the file.
  - Code examples where missing. Here's [an example of existing docs with code examples, please use `ruby` fenced code-blocks.
